### ISSUE TITLE
JavaScriptdagi o'zgartirish bo'lgan holatlar)

### ISSUE THREAD

**Issue by ghost** [abdulatifkhan/fizzbuzz-advanced-#1]
![image](https://user-images.githubusercontent.com/71978297/98634411-1bbcb680-2345-11eb-9efe-83d797db6532.png)

Formani submit hodisasini tepada yozgan yaxshi odatda :-)

**Comment by abdulatifkhan** [comment]
Bu yerda ham boshqa loyihani boshqasiga yozib qo'yibsiz, uni ham to'g'irlaymiz, rahmat)
