### ISSUE TITLE
Ko'dda belgilar qolib ketsa muammolar kelib chiqishi mumkin)

### ISSUE THREAD

**Issue by ghost** [abdulatifkhan/fizzbuzz-advanced-#2]
![image](https://user-images.githubusercontent.com/71978297/98634847-ca60f700-2345-11eb-9690-9965c164544e.png)

**Comment by abdulatifkhan** [comment]
Boshqa loyihadagi kamchilikni boshga loyihaga yozib qo'yibsiz, lekin bartaraf etamiz, rahmat)
