### ISSUE TITLE
Jsdagi to'g'irlanish kerak bo'lgan kamchiliklar :-)

### ISSUE THREAD

**Issue by ghost** [abdulatifkhan/fizzbuzz-advanced-#3]
![image](https://user-images.githubusercontent.com/71978297/98635503-efa23500-2346-11eb-8467-28ed0f6679b5.png)

Bu yerda ikki martta bir xil bo'sh array kerak emas 😉

**Comment by abdulatifkhan** [comment]
Tushunarli, kamchiliklarni bartaraf etdik)

**Comment by ghost** [comment]
😊

вт, 10 нояб. 2020 г. в 11:29, AbdulLateefKhan <notifications@github.com>:
