### ISSUE TITLE
Natijani ko'rsatishda kamchilik )

### ISSUE THREAD

**Issue by udilbar** [abdulatifkhan/fizzbuzz-advanced-#4]
![Screenshot_15](https://user-images.githubusercontent.com/68459485/98670187-25a9de00-2374-11eb-8632-59e35dc40793.png)
3 ga hamda 5 ga bo'linadigan sonlarni to'liq ko'rsatilmayapti. Muammoni hal qilishimiz kerak )

**Comment by abdulatifkhan** [comment]
Ustoz aytganlari bo'yicha qilganmiz. Meni yozganim vazifa bo'yicha to'g'ri, lekin mantiqan noto'g'ri, chunki vazifa shunday bo'lgan. Rahmat, inobatga olamiz)))

![image](https://user-images.githubusercontent.com/68887519/98670530-a2d55300-2374-11eb-9100-c8b871564934.png)
